version: '3.3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo-data:/data/db:rw
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
      - timetable-network
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: mongoadmin
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - timetable-network

  timetable:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./docker.env
    ports:
      - 8080:8080
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - timetable-network

volumes:
  mongo-data:
    name: mongo-data

networks:
  timetable-network:
    driver: bridge